PUNME_LIST = [
    "LAP TOP: Where the kitty sleeps.",
    "LOG ON: Makin' a woodstove hot.",
    "MODEM: Whutcha do to the hay fields.",
    "MAINFRAME: Holds up the barn roof.",
    "KEYBOARD: Whar you hang the dang truck keys.",
    "MICRO CHIP: What's in the bottom of the munchie bag.",
    "MONITOR: Keepin' an eye on the wood stove.",
    "WINDOWS: What to shut when it's cold outside.",
    "Two bytes meet.  The first byte asks, 'Are you ill?' The second byte replies, 'No, just feeling a bit off.'",
    "byte me;",
    "long john_silver;",
    "char broiled;",
    "string me_along;",
    "float valve;",
    "double jeopardy;",
    "struct by_lightning { ... };",
    "Object strongly;",
    "class warfare { ... };",
    "String cheese;",
    "Exception taken;",
    "long walk(short pier) { }",
    "int elligence;",
    "bool me_over;",
    "short circus;",
    "int eger; ",
    "char acter;",
    "bool ean;",
    "void* bowels;",
    "class Brick implements Throwable { }",
    "class Marathon implements Runnable { }",
    "class Novel implements Serializable { }",
    "class Human implements Cloneable { }",
    "while (e_coyote) {",
    "public MyTestCase(String man) { super(man); }",
    "throw (fit | up | something);",
    "I used to go fishing with Skrillex... But he kept dropping the bass.",
    "What's the worst thing about throwing a party in space? You have to planet.",
    "Yesterday a clown held a door open for me. I thought it was a nice jester.",
    "I ate too much Greek food. Now I falafel.",
    "How do you make antifreeze? Steal her blanket.",
    "It was an emotional wedding. Even the cake was in tiers.",
    "There was an explosion at a factory in France. De-brie everywhere.",
    "Why couldn't the bicycle stand up on its own? It was two tired.",
    "What's the best time to go to the dentist? Two-thirty."
]
